name: Python Lint

on:
  pull_request:
    branches: [main]

jobs:
  PythonLint:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Konstruktoid Python lint
        uses: konstruktoid/action-pylint@master
